{{- if and .Values.rbac.createUserRoles .Values.rbac.createViewerRoles }}
# permissions for end users to view cubriddbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cubriddb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cubrid-operator
    app.kubernetes.io/part-of: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "cubrid-operator.cubriddbViewClusterRoleName" . }}
rules:
- apiGroups:
  - k8s.cubrid.com
  resources:
  - cubriddbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cubrid.com
  resources:
  - cubriddbs/status
  verbs:
  - get
{{- end }}