{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled (eq .Values.webhook.certManagerType "external") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cubrid-operator.fullname" . }}-webhook-serving-cert
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "cubrid-operator-webhook.serviceName" . }}.{{ .Values.namespace | default .Release.Namespace }}.svc
  - {{ include "cubrid-operator-webhook.serviceName" . }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "cubrid-operator.fullname" . }}-webhook-selfsigned-issuer
  secretName: {{ include "cubrid-operator-webhook.secretName" . }}
  duration: {{ .Values.webhook.certificate.duration }}
  renewBefore: {{ .Values.webhook.certificate.renewBefore }}
  privateKey:
    algorithm: {{ .Values.webhook.certificate.privateKey.algorithm }}
    encoding: {{ .Values.webhook.certificate.privateKey.encoding }}
    size: {{ .Values.webhook.certificate.privateKey.size }}
  usages:
    - server auth
    - digital signature
    - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cubrid-operator.fullname" . }}-webhook-selfsigned-issuer
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selfSigned: {}
{{ end }} 