{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.secretName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
  ca.crt: ""
{{- end }}  