{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubrid-operator-webhook.secretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
  ca.crt: ""
{{- end }}  