{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.labels" . | nindent 4 }}
  name: {{ include "cubrid-operator-webhook.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}  