{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubrid-operator-webhook.secretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhook.secret.tls.crt }}
  tls.key: {{ .Values.webhook.secret.tls.key }}
{{- end }}  