{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-webhook-dep
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName }}-webhook-dep
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $fullName }}-webhook-dep
        control-plane: controller-manager  
    spec:
      serviceAccountName: {{ include "cubrid-operator-webhook.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ $fullName }}-webhook-dep
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["./manager"]
        args:
          - webhook
          - --webhook-cert-dir={{ .Values.webhook.certDir }}
          - --webhook-port={{ .Values.webhook.ports.webhook }}
          - --webhook-service-name={{ include "cubrid-operator-webhook.serviceName" . }}
          - --webhook-namespace={{ .Values.namespace | default .Release.Namespace }}
          - --webhook-secret-name={{ .Values.webhook.secretName }}
          - --webhook-mutating-name={{ include "cubrid-operator.fullname" . }}-webhook-mutating
          - --webhook-validating-name={{ include "cubrid-operator.fullname" . }}-webhook-validating
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - name: webhook
          containerPort: {{ .Values.webhook.ports.webhook }}
        - name: probe
          containerPort: {{ .Values.webhook.ports.probe }}
        - name: metrics
          containerPort: {{ .Values.webhook.ports.metrics }}
        volumeMounts:
        - name: cert-dir
          mountPath: {{ .Values.webhook.certDir }}
          readOnly: false
        {{- with .Values.webhook.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: probe
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: probe
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
      volumes:
      - name: cert-dir
        secret:
          secretName: {{ .Values.webhook.secretName }}
{{- end }}