{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ $fullName }}-webhook-mutating
  annotations:
    {{- if eq .Values.webhook.certManagerType "external" }}
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Values.webhook.secretName }}"
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cubrid-operator-webhook.serviceName" . }}
      namespace: {{ .Values.namespace | default .Release.Namespace }}
      path: /mutate-k8s-cubrid-com-v1-backupdb
    {{- if eq .Values.webhook.certManagerType "external" }}
    caBundle: {{ .Values.webhook.cabundle }}
    {{- end }}
  failurePolicy: Fail
  name: mbackupdb.kb.io
  rules:
  {{- range .Values.webhook.brules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    apiVersions:
      {{- range .apiVersions }}
      - {{ . | quote }}
      {{- end }}
    operations:
      {{- range .operations }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
{{- end }}
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cubrid-operator-webhook.serviceName" . }}
      namespace: {{ .Values.namespace | default .Release.Namespace }}
      path: /mutate-k8s-cubrid-com-v1-cubriddb
    {{- if eq .Values.webhook.certManagerType "external" }}
    caBundle: {{ .Values.webhook.cabundle }}
    {{- end }}
  failurePolicy: Fail
  name: mcubriddb.kb.io
  rules:
  {{- range .Values.webhook.crules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    apiVersions:
      {{- range .apiVersions }}
      - {{ . | quote }}
      {{- end }}
    operations:
      {{- range .operations }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
{{- end }}
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ $fullName }}-webhook-validating
  annotations:
    {{- if eq .Values.webhook.certManagerType "external" }}
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Values.webhook.secretName }}"
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cubrid-operator-webhook.serviceName" . }}
      namespace: {{ .Values.namespace | default .Release.Namespace }}
      path: /validate-k8s-cubrid-com-v1-backupdb
    {{- if eq .Values.webhook.certManagerType "external" }}
    caBundle: {{ .Values.webhook.cabundle }}
    {{- end }}
  failurePolicy: Fail
  name: vbackupdb.kb.io
  rules:
  {{- range .Values.webhook.brules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    apiVersions:
      {{- range .apiVersions }}
      - {{ . | quote }}
      {{- end }}
    operations:
      {{- range .operations }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cubrid-operator-webhook.serviceName" . }}
      namespace: {{ .Values.namespace | default .Release.Namespace }}
      path: /validate-k8s-cubrid-com-v1-cubriddb
    {{- if eq .Values.webhook.certManagerType "external" }}
    caBundle: {{ .Values.webhook.cabundle }}
    {{- end }}
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  name: vcubriddb.kb.io
  rules:
  {{- range .Values.webhook.crules }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . | quote }}
      {{- end }}
    apiVersions:
      {{- range .apiVersions }}
      - {{ . | quote }}
      {{- end }}
    operations:
      {{- range .operations }}
      - {{ . | quote }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
  sideEffects: None
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 5 }}
{{- end }}