{{ if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled }}
{{ $fullName := include "cubrid-operator.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "cubrid-operator-webhook.serviceName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    app: {{ $fullName }}-webhook-dep
{{- end }}    