apiVersion: v2
name: cubrid-operator
description: A Helm chart for Cubrid Operator
home: https://github.com/CUBRID/cubrid-operator
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.30.0-0"
maintainers:
  - email: airnet@cubrid.com
    name: Dooho Kang
keywords:
  - cubrid
  - cubrid HA
  - cubrid-operator
# dependencies:
#   - name: cubrid-operator-crds
#     version: "0.0.1"
#     condition: crds.enabled
#     repository: file://../cubrid-operator-crds
