apiVersion: v2
name: cubrid-operator-crds
description: cubrid-operator CRDs
home: https://github.com/CUBRID/cubrid-operator
type: application
version: 0.0.1
appVersion: "11.4.0"
kubeVersion: ">=1.30.0-0"
maintainers:
  - email: airnet@cubrid.com
    name: Dooho Kang
keywords:
  - cubrid
  - cubrid HA
  - cubrid-operator
