apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: cubrid-webhook-service
  namespace: cubrid
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    app: cubrid-operator-webhook