---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cubrid-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cubrid-webhook-service
      namespace: cubrid
      path: /mutate-k8s-cubrid-com-v1-backupdb
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvRENDQWdtZ0F3SUJBZ0lKQUlNWEwzdUMyUGVvTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2t4Q3pBSkJnTlYKQkFZVEFrdFBNUTR3REFZRFZRUUlEQVZMVDFKRlFURU9NQXdHQTFVRUJ3d0ZVMFZQVlV3eER6QU5CZ05WQkFvTQpCa05WUWxKSlJERVBNQTBHQTFVRUN3d0dZM1ZpY21sa01SZ3dGZ1lEVlFRRERBOURWVUpTU1VRZ1QzQmxjbUYwCmIzSXdIaGNOTWpReE1URXlNRFV5TkRFd1doY05NelF4TVRFd01EVXlOREV3V2pCcE1Rc3dDUVlEVlFRR0V3SkwKVHpFT01Bd0dBMVVFQ0F3RlMwOVNSVUV4RGpBTUJnTlZCQWNNQlZORlQxVk1NUTh3RFFZRFZRUUtEQVpEVlVKUwpTVVF4RHpBTkJnTlZCQXNNQm1OMVluSnBaREVZTUJZR0ExVUVBd3dQUTFWQ1VrbEVJRTl3WlhKaGRHOXlNSUdmCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FETHUxMVdhL3pJV2Niall6RmtzcUhpTjhIM21aaS8KT0R2TjFBM3VDdHFVTkxMMXRxSlczejlpU050TU5FTDNkUThMdXZlTnhvRjJxeEw3MUZOQjBRMkxpREc1aWV2Vwp3djlibVNPcEdSWk5seER3L0hZWmw1YWVmV3h0TDFsdW5JaWRSMjF4L0tMRmYrNkF6eFJBSU9QcksxRzB4c0orCkVicHJvL0s3THlPYWp3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIKKzdVd0h3WURWUjBqQkJnd0ZvQVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIrN1V3REFZRFZSMFRCQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUUNnekp4TDFGSjNpQ3JQYkJHVWhxWEdwVng3TDUxZVBHR3JjdGdoClFVUkNnWU1rVEpLellLWTVBM2lYYUNNQzJaSzdFc1VBMjM0U0d0L1JVbnNabThhQVRaS3JxWFVGckVvU1dzMVQKaFNTV2pvbzZUVlVUOEt3YkkwTFdYcVpPL2FXd0NmZVNtNVlaWlhMVU9WUWpZaVgwSmhCVEQwU0V2REhYK1ZVVgp1ckJGRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Fail
  name: mbackupdb.kb.io
  rules:
  - apiGroups:
    - k8s.cubrid.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cubrid-webhook-service
      namespace: cubrid
      path: /mutate-k8s-cubrid-com-v1-cubriddb
    #url: https://localhost:9443/mutate-k8s-cubrid-com-v1-cubriddb
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvRENDQWdtZ0F3SUJBZ0lKQUlNWEwzdUMyUGVvTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2t4Q3pBSkJnTlYKQkFZVEFrdFBNUTR3REFZRFZRUUlEQVZMVDFKRlFURU9NQXdHQTFVRUJ3d0ZVMFZQVlV3eER6QU5CZ05WQkFvTQpCa05WUWxKSlJERVBNQTBHQTFVRUN3d0dZM1ZpY21sa01SZ3dGZ1lEVlFRRERBOURWVUpTU1VRZ1QzQmxjbUYwCmIzSXdIaGNOTWpReE1URXlNRFV5TkRFd1doY05NelF4TVRFd01EVXlOREV3V2pCcE1Rc3dDUVlEVlFRR0V3SkwKVHpFT01Bd0dBMVVFQ0F3RlMwOVNSVUV4RGpBTUJnTlZCQWNNQlZORlQxVk1NUTh3RFFZRFZRUUtEQVpEVlVKUwpTVVF4RHpBTkJnTlZCQXNNQm1OMVluSnBaREVZTUJZR0ExVUVBd3dQUTFWQ1VrbEVJRTl3WlhKaGRHOXlNSUdmCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FETHUxMVdhL3pJV2Niall6RmtzcUhpTjhIM21aaS8KT0R2TjFBM3VDdHFVTkxMMXRxSlczejlpU050TU5FTDNkUThMdXZlTnhvRjJxeEw3MUZOQjBRMkxpREc1aWV2Vwp3djlibVNPcEdSWk5seER3L0hZWmw1YWVmV3h0TDFsdW5JaWRSMjF4L0tMRmYrNkF6eFJBSU9QcksxRzB4c0orCkVicHJvL0s3THlPYWp3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIKKzdVd0h3WURWUjBqQkJnd0ZvQVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIrN1V3REFZRFZSMFRCQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUUNnekp4TDFGSjNpQ3JQYkJHVWhxWEdwVng3TDUxZVBHR3JjdGdoClFVUkNnWU1rVEpLellLWTVBM2lYYUNNQzJaSzdFc1VBMjM0U0d0L1JVbnNabThhQVRaS3JxWFVGckVvU1dzMVQKaFNTV2pvbzZUVlVUOEt3YkkwTFdYcVpPL2FXd0NmZVNtNVlaWlhMVU9WUWpZaVgwSmhCVEQwU0V2REhYK1ZVVgp1ckJGRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Fail
  name: mcubriddb.kb.io
  rules:
  - apiGroups:
    - k8s.cubrid.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cubriddbs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cubrid-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cubrid-webhook-service
      namespace: cubrid
      path: /validate-k8s-cubrid-com-v1-backupdb
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvRENDQWdtZ0F3SUJBZ0lKQUlNWEwzdUMyUGVvTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2t4Q3pBSkJnTlYKQkFZVEFrdFBNUTR3REFZRFZRUUlEQVZMVDFKRlFURU9NQXdHQTFVRUJ3d0ZVMFZQVlV3eER6QU5CZ05WQkFvTQpCa05WUWxKSlJERVBNQTBHQTFVRUN3d0dZM1ZpY21sa01SZ3dGZ1lEVlFRRERBOURWVUpTU1VRZ1QzQmxjbUYwCmIzSXdIaGNOTWpReE1URXlNRFV5TkRFd1doY05NelF4TVRFd01EVXlOREV3V2pCcE1Rc3dDUVlEVlFRR0V3SkwKVHpFT01Bd0dBMVVFQ0F3RlMwOVNSVUV4RGpBTUJnTlZCQWNNQlZORlQxVk1NUTh3RFFZRFZRUUtEQVpEVlVKUwpTVVF4RHpBTkJnTlZCQXNNQm1OMVluSnBaREVZTUJZR0ExVUVBd3dQUTFWQ1VrbEVJRTl3WlhKaGRHOXlNSUdmCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FETHUxMVdhL3pJV2Niall6RmtzcUhpTjhIM21aaS8KT0R2TjFBM3VDdHFVTkxMMXRxSlczejlpU050TU5FTDNkUThMdXZlTnhvRjJxeEw3MUZOQjBRMkxpREc1aWV2Vwp3djlibVNPcEdSWk5seER3L0hZWmw1YWVmV3h0TDFsdW5JaWRSMjF4L0tMRmYrNkF6eFJBSU9QcksxRzB4c0orCkVicHJvL0s3THlPYWp3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIKKzdVd0h3WURWUjBqQkJnd0ZvQVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIrN1V3REFZRFZSMFRCQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUUNnekp4TDFGSjNpQ3JQYkJHVWhxWEdwVng3TDUxZVBHR3JjdGdoClFVUkNnWU1rVEpLellLWTVBM2lYYUNNQzJaSzdFc1VBMjM0U0d0L1JVbnNabThhQVRaS3JxWFVGckVvU1dzMVQKaFNTV2pvbzZUVlVUOEt3YkkwTFdYcVpPL2FXd0NmZVNtNVlaWlhMVU9WUWpZaVgwSmhCVEQwU0V2REhYK1ZVVgp1ckJGRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==      
  failurePolicy: Fail
  name: vbackupdb.kb.io
  rules:
  - apiGroups:
    - k8s.cubrid.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cubrid-webhook-service
      namespace: cubrid
      path: /validate-k8s-cubrid-com-v1-cubriddb
    #url: https://localhost:9443/mutate-k8s-cubrid-com-v1-cubriddb
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvRENDQWdtZ0F3SUJBZ0lKQUlNWEwzdUMyUGVvTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2t4Q3pBSkJnTlYKQkFZVEFrdFBNUTR3REFZRFZRUUlEQVZMVDFKRlFURU9NQXdHQTFVRUJ3d0ZVMFZQVlV3eER6QU5CZ05WQkFvTQpCa05WUWxKSlJERVBNQTBHQTFVRUN3d0dZM1ZpY21sa01SZ3dGZ1lEVlFRRERBOURWVUpTU1VRZ1QzQmxjbUYwCmIzSXdIaGNOTWpReE1URXlNRFV5TkRFd1doY05NelF4TVRFd01EVXlOREV3V2pCcE1Rc3dDUVlEVlFRR0V3SkwKVHpFT01Bd0dBMVVFQ0F3RlMwOVNSVUV4RGpBTUJnTlZCQWNNQlZORlQxVk1NUTh3RFFZRFZRUUtEQVpEVlVKUwpTVVF4RHpBTkJnTlZCQXNNQm1OMVluSnBaREVZTUJZR0ExVUVBd3dQUTFWQ1VrbEVJRTl3WlhKaGRHOXlNSUdmCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FETHUxMVdhL3pJV2Niall6RmtzcUhpTjhIM21aaS8KT0R2TjFBM3VDdHFVTkxMMXRxSlczejlpU050TU5FTDNkUThMdXZlTnhvRjJxeEw3MUZOQjBRMkxpREc1aWV2Vwp3djlibVNPcEdSWk5seER3L0hZWmw1YWVmV3h0TDFsdW5JaWRSMjF4L0tMRmYrNkF6eFJBSU9QcksxRzB4c0orCkVicHJvL0s3THlPYWp3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIKKzdVd0h3WURWUjBqQkJnd0ZvQVVQTHhkTnI4Q2J6UzVOd1BPZjZOYi92QVIrN1V3REFZRFZSMFRCQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUUNnekp4TDFGSjNpQ3JQYkJHVWhxWEdwVng3TDUxZVBHR3JjdGdoClFVUkNnWU1rVEpLellLWTVBM2lYYUNNQzJaSzdFc1VBMjM0U0d0L1JVbnNabThhQVRaS3JxWFVGckVvU1dzMVQKaFNTV2pvbzZUVlVUOEt3YkkwTFdYcVpPL2FXd0NmZVNtNVlaWlhMVU9WUWpZaVgwSmhCVEQwU0V2REhYK1ZVVgp1ckJGRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Fail
  name: vcubriddb.kb.io
  rules:
  - apiGroups:
    - k8s.cubrid.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cubriddbs
  sideEffects: None