apiVersion: k8s.cubrid.com/v1
kind: CubridDB
metadata:
  name: cubrid-replica

spec:
  image: airnet73/cubrid:v11.3.1.3
  updateStrategy:
    type: "RollingUpdate" 
    rollingUpdate:
      partition: 0        
      maxUnavailable: 3
  replication:
    enable: true
    replicas: 1
    hamodeType:
      type: "replica"
      cubridRef:
        name: "cubrid-master"
  
  broker:
  - appl_max: 40
    appl_min: 5
    brokerType: RW
    name: rep-broker1-svc
    port: 30000
    servicePort: 30100
    serviceType: NodePort
  - appl_max: 40
    appl_min: 5
    brokerType: RW
    name: rep-broker2-svc
    port: 33000
    servicePort: 30101
    serviceType: NodePort
