apiVersion: k8s.cubrid.com/v1
kind: BackupDB
metadata:
  labels:
    app.kubernetes.io/name: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupdb-test
spec:
  cubridDBRef:
    name: cubrid-test-0
    namespace: default
    dbName: demodb
  commandArgs:
    filepath: "/share/scripts/backupdb.sh"
    args:
      - "start"
      - "demodb"
      - "0"
      - "5"
  storageRef:
    storageType: backup-storage-type