apiVersion: k8s.cubrid.com/v1
kind: CubridDB
metadata:
  name: ha-ms

spec:
  initContainerImage: busybox
  image: airnet73/cubrid
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0        
      maxUnavailable: 3
  replication:
    enable: true
    replicas: 2
    hamodeType:
      type: master-slave
  cmsService:
    type: Ingress
    startPort: 31000
    port: 8001
  broker:
  - name: ms-broker1-svc
    port: 30000
    servicePort: 30100
    serviceType: NodePort
  - name: ms-broker2-svc
    port: 33000
    servicePort: 30101
    serviceType: NodePort
