apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubrid-operator-webhook
  namespace: cubrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubrid-operator-webhook
  template:
    metadata:
      labels:
        app: cubrid-operator-webhook
        control-plane: controller-manager  
    spec:
      serviceAccountName: cubrid-webhook-sa
      containers:
      - name: cubrid-operator-webhook
        image: airnet73/operator:latest
        args: ["webhook"]  
        ports:
        - containerPort: 4443
          name: webhook
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-server-cert
