apiVersion: k8s.cubrid.com/v1
kind: BackupDB
metadata:
  labels:
    app.kubernetes.io/name: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupdb-demodb
spec:
  cubridDBRef:
    name: cubriddb-test2-0
    namespace: default
    dbName: cubdb
  schedules:
  - schedule: "* * * * *"
    filepath: "/home/cubrid/CUBRID/share/scripts/backupdb.sh"
    args:
      - "start"
      - "testdb"
      - "0"
      - "7"
  - schedule: "*/3 * * * *"
    filepath: "/home/cubrid/CUBRID/share/scripts/backupdb.sh"
    args:
      - "start"
      - "testdb"
      - "1"
      - "7"        
  storageRef:
    storageType: backupdb-storage-cubriddb-test2-0
  # TODO(user): Add fields here
