apiVersion: k8s.cubrid.com/v1
kind: CubridDB
metadata:
  labels:
    app.kubernetes.io/name: cubrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: cubrid-test2
spec:
  image: airnet73/cubrid:v11.3.1.2
  replication:
    enable: false